### ISSUE TITLE
It crashes when hitting a mob

### ISSUE THREAD

**Issue by VerdeCreeper** [Elem8100/MapleNecrocer#52]
Right before it closes, this pop up 

![Image](https://github.com/user-attachments/assets/ae7881a3-1e70-4c62-94ce-38284c48fefd)

**Comment by Elem8100** [comment]
fixed

**Comment by VerdeCreeper** [comment]
Nope. Still happening.

Does have something to do with the filepath? Does the Maplestory folder should be on the MapleNecrocer folder?

**Comment by Elem8100** [comment]
Which version/region ?

**Comment by VerdeCreeper** [comment]
Thanks! But now I have another issue. When I open the skill tab, it freezes and crashes. I don't have that problem with the other tabs. Can you fix that please?

**Comment by VerdeCreeper** [comment]
Solved. Also a small thing; Can you please add the option to hide the damage numbers and skills? And well the option for mobs to respawn? Thanks.

**Comment by Elem8100** [comment]
Those features are not required for most people. I have not plan to do that. You have to modify the source code for your own.

**Comment by VerdeCreeper** [comment]
Where do I find the source code?

**Comment by Elem8100** [comment]
https://www.mediafire.com/file/feufvecdmu95plr/MapleNecrocer.zip/file

**Comment by VerdeCreeper** [comment]
Thanks
